### ISSUE TITLE
Collector: Getting it to work with Oracle and/or SQL Server

### ISSUE THREAD

**Issue by eri-blan** [hajkmap/Hajk#1275]
**Describe the bug**
I´m trying to get the Collector plugin to work with either Oracle or SQL Server. However, as i press send (Skicka) the error below. I can´t see where geom is undefined exactly but I´m far from an expert in Hajk code. Any clues on what could be wrong? Has anyone been successful with either Oracle or SQL Server?

```
Uncaught TypeError: Cannot read properties of undefined (reading 'geom')
    at E (xml.js:491:28)
    at _ (xml.js:535:3)
    at t.writeFeatureElement (GML3.js:878:5)
    at N (WFS.js:792:5)
    at xml.js:275:16
    at E (xml.js:491:58)
    at _ (xml.js:535:3)
    at Z (WFS.js:712:3)
    at t.writeTransaction (WFS.js:613:7)
    at e.value (CollectorModel.js:85:19)
```

**To Reproduce**

Using SQL Server
Create a table for instance like this:
```
CREATE TABLE [dbo].[REDIGERING_TEST2](
	[OK_ID] [int] IDENTITY(1,1) NOT NULL,
	[GEOM] [geometry] NULL,
	[TEXT] [nvarchar](255) NULL,
	[TEXT2] [nvarchar](255) NULL)
```
Follow the Wiki-page on the Collector plugin.

**Comment by jacobwod** [comment]
I don't think that `geom` is undefined. It's rather the object on which we try to access the property of `geom` that's undefined, e.g. `someObject.geom` would produce this error if `someObject === undefined`. 

Hence, I guess the entire `Feature` is undefined.

**Comment by eri-blan** [comment]
You´re right. I managed to get further though. Perhaps the previous error occurs when there is no object already in the database.

A problem persists though where it looks like QGIS-server only recognizes the name <geometry> like for instance in the post request below:

`<Transaction xmlns="http://www.opengis.net/wfs" service="WFS" version="1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd"><Insert><REDIGERING_TEST_SQL_SERVER2><geometry><Point xmlns="http://www.opengis.net/gml" srsName="EPSG:3009"><pos srsDimension="2">167017.6 6574344</pos></Point></geometry><OK_ID>243</OK_ID><TEXT>243</TEXT><TEXT2>243</TEXT2></REDIGERING_TEST_SQL_SERVER2></Insert></Transaction>`

The above request body is made when using the Edit plugin, and it works. The below request body is made with the Collector plugin using the same data source. This request times out (499 response).

`<Transaction xmlns="http://www.opengis.net/wfs" service="WFS" version="1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd"><Insert><REDIGERING_TEST_SQL_SERVER2><geom><Point xmlns="http://www.opengis.net/gml" srsName="EPSG:3009"><pos srsDimension="2">165487.89448089595 6574231.894480895</pos></Point></geom><OK_ID>123456</OK_ID><TEXT>text</TEXT><TEXT2>text</TEXT2></REDIGERING_TEST_SQL_SERVER2></Insert></Transaction>
`
