### ISSUE TITLE
LayerSwitcher: Attribute table seems to crash whenever the layer contains a dateTime field using QGIS Server

### ISSUE THREAD

**Issue by eri-blan** [hajkmap/Hajk#1540]
**Describe the bug**
When activating the setting to enable the attribute table, the Hajk client crashes (becomes completely white) when clicking on the attribute table button if the layer contains a dateTime field, for instance Date in Oracle or timestamp in PostgreSQL.
![image](https://github.com/user-attachments/assets/aeed57c8-f45d-4f3f-8e37-aeab71572c8e)

The dateTime field seems to look something like this in the response from QGIS Server:

(GetFeature)

`"DATUM": "2022-04-28T00:00:00.000" `

(DescribeFeatureType)
```
  {
                    "alias": "Dating",
                    "localType": "date",
                    "name": "DATUM",
                    "nillable": "true",
                    "type": "date"
  }
```

I have tried altering the settings below for the layer in QGIS, but to no effect. MUI seems to only accept Date() objects after all. Perhaps valueGetter can be used to convert the dateTime strings somehow? 
[Link to MUI docs](https://mui.com/x/react-data-grid/column-definition/#converting-types)
![image](https://github.com/user-attachments/assets/a6ec47e0-b5c9-4ee0-8d3c-6d4be290e940)

**To Reproduce**
Activate the functionality in Admin for a layer containing any number of dateTime fields. Click on the attribute table icon.

The following type of error will display:

`ERROR
MUI: `date` column type only accepts `Date` objects as values.
Use `valueGetter` to transform the value into a `Date` object.
Row ID: 0, field: "DATUM".
Error: MUI: `date` column type only accepts `Date` objects as values.
Use `valueGetter` to transform the value into a `Date` object.
Row ID: 0, field: "DATUM".
    at throwIfNotDateObject (http://localhost:3000/static/js/bundle.js:67040:11)
    at Object.gridDateFormatter [as valueFormatter] (http://localhost:3000/static/js/bundle.js:67052:3)
    at Object.getCellParams (http://localhost:3000/static/js/bundle.js:87296:38)
    at http://localhost:3000/static/js/bundle.js:70224:41
    at applySelector (http://localhost:3000/static/js/bundle.js:90112:10)
    at useGridSelector (http://localhost:3000/static/js/bundle.js:90132:20)
    at http://localhost:3000/static/js/bundle.js:70219:107
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:151795:22)
    at updateForwardRef (http://localhost:3000/static/js/bundle.js:154364:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:156411:20)`

**Expected behavior**
The attribute table shows up as expected.

**Additional context**
Tested using Oracle and PostgreSQL. Using QGIS/QGIS Server 3.34. I have not tested it with for instance Geoserver. Hajk version 3.14 RC1.

**Comment by jacobwod** [comment]
Hi @eri-blan. The clear description you provide got me thinking and I think the solution could be as simple as adding rows 631-633, as in the screenshot below:

```js
````
